Update HasMetaTrait.php
Conflict with method "save" if Zizaco/confide installed
Fatal error: Method 'save' declared in multiple traits in app/models/User.php
changed save() to doSave()